import type { Config } from "tailwindcss";
const defaultTheme = require("tailwindcss/defaultTheme");

const config: Config = {
  content: ["./dist/index.html","./src/**/*.{js,ts,jsx,tsx,mdx}",],
  theme: {
    colors: {
			black: "#000",
			white: "#fff",
			transparent: "transparent",
			current: "currentColor",

			"theme-background": "var(--theme-background-color)",
			"theme-secondary-background": "var(--theme-secondary-background-color)",

			"theme-text": "var(--theme-text-color)",
			"theme-secondary-text": "var(--theme-secondary-text-color)",

			"theme-primary-50": "var(--theme-color-primary-50)",
			"theme-primary-100": "var(--theme-color-primary-100)",
			"theme-primary-200": "var(--theme-color-primary-200)",
			"theme-primary-300": "var(--theme-color-primary-300)",
			"theme-primary-400": "var(--theme-color-primary-400)",
			"theme-primary-500": "var(--theme-color-primary-500)",
			"theme-primary-600": "var(--theme-color-primary-600)",
			"theme-primary-700": "var(--theme-color-primary-700)",
			"theme-primary-800": "var(--theme-color-primary-800)",
			"theme-primary-900": "var(--theme-color-primary-900)",

			"theme-primary-reverse-50": "var(--theme-color-primary-reverse-50)",
			"theme-primary-reverse-100": "var(--theme-color-primary-reverse-100)",
			"theme-primary-reverse-200": "var(--theme-color-primary-reverse-200)",
			"theme-primary-reverse-300": "var(--theme-color-primary-reverse-300)",
			"theme-primary-reverse-400": "var(--theme-color-primary-reverse-400)",
			"theme-primary-reverse-500": "var(--theme-color-primary-reverse-500)",
			"theme-primary-reverse-600": "var(--theme-color-primary-reverse-600)",
			"theme-primary-reverse-700": "var(--theme-color-primary-reverse-700)",
			"theme-primary-reverse-800": "var(--theme-color-primary-reverse-800)",
			"theme-primary-reverse-900": "var(--theme-color-primary-reverse-900)",

			"theme-secondary-50": "var(--theme-color-secondary-50)",
			"theme-secondary-100": "var(--theme-color-secondary-100)",
			"theme-secondary-200": "var(--theme-color-secondary-200)",
			"theme-secondary-300": "var(--theme-color-secondary-300)",
			"theme-secondary-400": "var(--theme-color-secondary-400)",
			"theme-secondary-500": "var(--theme-color-secondary-500)",
			"theme-secondary-600": "var(--theme-color-secondary-600)",
			"theme-secondary-700": "var(--theme-color-secondary-700)",
			"theme-secondary-800": "var(--theme-color-secondary-800)",
			"theme-secondary-900": "var(--theme-color-secondary-900)",
			"theme-secondary-900-rgba": "rgba(var(--theme-color-secondary-900-rgb), var(--tw-bg-opacity))",

			"theme-success-50": "var(--theme-color-success-50)",
			"theme-success-100": "var(--theme-color-success-100)",
			"theme-success-200": "var(--theme-color-success-200)",
			"theme-success-300": "var(--theme-color-success-300)",
			"theme-success-400": "var(--theme-color-success-400)",
			"theme-success-500": "var(--theme-color-success-500)",
			"theme-success-600": "var(--theme-color-success-600)",
			"theme-success-700": "var(--theme-color-success-700)",
			"theme-success-800": "var(--theme-color-success-800)",
			"theme-success-900": "var(--theme-color-success-900)",

			"theme-warning-50": "var(--theme-color-warning-50)",
			"theme-warning-100": "var(--theme-color-warning-100)",
			"theme-warning-200": "var(--theme-color-warning-200)",
			"theme-warning-300": "var(--theme-color-warning-300)",
			"theme-warning-400": "var(--theme-color-warning-400)",
			"theme-warning-500": "var(--theme-color-warning-500)",
			"theme-warning-600": "var(--theme-color-warning-600)",
			"theme-warning-700": "var(--theme-color-warning-700)",
			"theme-warning-800": "var(--theme-color-warning-800)",
			"theme-warning-900": "var(--theme-color-warning-900)",

			"theme-danger-50": "var(--theme-color-danger-50)",
			"theme-danger-100": "var(--theme-color-danger-100)",
			"theme-danger-200": "var(--theme-color-danger-200)",
			"theme-danger-300": "var(--theme-color-danger-300)",
			"theme-danger-400": "var(--theme-color-danger-400)",
			"theme-danger-500": "var(--theme-color-danger-500)",
			"theme-danger-600": "var(--theme-color-danger-600)",
			"theme-danger-700": "var(--theme-color-danger-700)",
			"theme-danger-800": "var(--theme-color-danger-800)",
			"theme-danger-900": "var(--theme-color-danger-900)",

			"theme-hint-50": "var(--theme-color-hint-50)",
			"theme-hint-100": "var(--theme-color-hint-100)",
			"theme-hint-200": "var(--theme-color-hint-200)",
			"theme-hint-300": "var(--theme-color-hint-300)",
			"theme-hint-400": "var(--theme-color-hint-400)",
			"theme-hint-500": "var(--theme-color-hint-500)",
			"theme-hint-600": "var(--theme-color-hint-600)",
			"theme-hint-700": "var(--theme-color-hint-700)",
			"theme-hint-800": "var(--theme-color-hint-800)",
			"theme-hint-900": "var(--theme-color-hint-900)",

			"theme-info-50": "var(--theme-color-info-50)",
			"theme-info-100": "var(--theme-color-info-100)",
			"theme-info-200": "var(--theme-color-info-200)",
			"theme-info-300": "var(--theme-color-info-300)",
			"theme-info-400": "var(--theme-color-info-400)",
			"theme-info-500": "var(--theme-color-info-500)",
			"theme-info-600": "var(--theme-color-info-600)",
			"theme-info-700": "var(--theme-color-info-700)",
			"theme-info-800": "var(--theme-color-info-800)",
			"theme-info-900": "var(--theme-color-info-900)",

			"theme-red-50": "var(--theme-color-red-50)",
			"theme-red-100": "var(--theme-color-red-100)",
			"theme-red-200": "var(--theme-color-red-200)",
			"theme-red-300": "var(--theme-color-red-300)",
			"theme-red-400": "var(--theme-color-red-400)",
			"theme-red-500": "var(--theme-color-red-500)",
			"theme-red-600": "var(--theme-color-red-600)",
			"theme-red-700": "var(--theme-color-red-700)",
			"theme-red-800": "var(--theme-color-red-800)",
			"theme-red-900": "var(--theme-color-red-900)",

			"theme-danger-info-text": "var(--theme-danger-info-text)",
			"theme-danger-info-background": "var(--theme-danger-info-background)",
			"theme-danger-info-border": "var(--theme-danger-info-border)",
		},
    extend: {
			opacity: {
				10: "0.1",
				50: "0.50",
				90: "0.9",
			},
			fontFamily: {
				sans: ["Inter", ...defaultTheme.fontFamily.sans],
			},
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
